### ISSUE TITLE
Weird behaviour when using floating-ui within a skewed element

### ISSUE THREAD

**Issue by Middlerun** [floating-ui/floating-ui#2516] opened 2023-08-29 10:25 UTC
**Describe the bug**
This is a bit of a niche issue. I'm building a website where the entire UI is skewed by 5 degrees. This is somehow throwing off the calculations for some of the middlewares, including `offset` and `size`.

**To Reproduce**
https://codesandbox.io/s/unruffled-dijkstra-kgt8vs?file=/src/App.js

1. Open sandbox
2. Without any skew, the offset is correct and the size middleware sets the correct height for the floating element
3. Click the "toggle skew" button
4. Now the floating element is shorter than it should be. The amount of extra space at the bottom depends on the viewport width - wider viewport leads to more empty space.
5. The offset is also incorrect. It varies based on both viewport width and height.

**Expected behavior**
- For `offset`, the gap between the element should be the same as normal.
- For `size`... well it's not entirely clear what the correct behaviour would be. With a padding value of 8px, should the **lowest** point (bottom left corner) be 8px away from the viewport edge? Or should it be the middle of the bottom edge that's 8px from the viewport edge, since that's the axis of the skew? I'm not sure but either of those would be preferable to the current behaviour.

**Screenshots**
![image](https://github.com/floating-ui/floating-ui/assets/568499/5bd11c33-54ea-4be1-81d0-841bb3f0baee)

**Context:**
 - OS: Windows
 - Browser: Chrome, Firefox
 - Version: @floating-ui/react-dom 2.0.2

**Comment by Middlerun** [comment] 2023-09-04 12:29
I've tracked the problem down to the way `elementClientRect` is calculated from `packages/core/src/detectOverflow.ts`. It seems the `convertOffsetParentRelativeRectToViewportRelativeRect` function isn't designed to handle this scenario.

**Comment by atomiks** [comment] 2023-09-06 07:50
That wouldn't explain the `offset` being wrong though I don't think? Only the clipping detection

**Comment by atomiks** [comment] 2023-09-20 08:54
I found a decent workaround for this by portaling the floating element outside of the skewed app container (e.g. into the body). While you still need to fiddle with the padding and offset a bit, it's no longer variable with respect to the viewport at least, so it's reliable/deterministic. 

https://codesandbox.io/s/hopeful-kepler-q3y8tj?file=/src/App.js

With how niche the issue is and the impact it would cause on bundle size to handle that most people will never see or need to use, I'm going to close it as wontfix.

**Closed by atomiks** 2023-09-20 08:54 UTC
Labels: bug

**Comment by Middlerun** [comment] 2023-09-20 10:02
Fair enough. Thanks for looking into it, I'll give that method a try. 🙂
