### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by raja-OX** [floating-ui/floating-ui#2338] opened 2023-05-23 06:35 UTC
Whenever there is no space tooltip this error message will show.

**Comment by atomiks** [comment] 2023-05-23 06:38
Duplicate of: https://github.com/floating-ui/floating-ui/issues/1740
Please provide a reproduction there if you can.

**Closed** 2023-05-23 06:42 UTC
Labels: Bug, NEEDS: triage

**Comment by raja-OX** [comment] 2023-05-23 07:26
[Screencast from 23-05-23 12:52:41 PM IST.webm](https://github.com/floating-ui/floating-ui/assets/112232124/4537ba6c-fcf7-4130-b677-d3bec1040555)

When I click any of the dates here, I am opening the floating UI modal. Since the size is bigger than the screen I am getting this error.

**Comment by atomiks** [comment] 2023-05-23 07:40
Make sure you set this CSS on the floating element:

1. A fixed width (e.g. `width: 200px`) OR `width: max-content`
2. Plus, `max-width: 100vw` to ensure it's not wider than the viewport width

**Comment by raja-OX** [comment] 2023-05-23 08:26
@atomiks Thanks, it's working well.
