### ISSUE TITLE
 Cannot read properties of null (reading 'assignedSlot')

### ISSUE THREAD

**Issue by kakserpom** [floating-ui/floating-ui#2267] opened 2023-04-01 05:52 UTC
**Describe the bug**

MainLayout.tsx:32 TypeError: Cannot read properties of null (reading 'assignedSlot')
    at getParentNode (getParentNode.js?v=2be83490:12:13)
    at getScrollParent (getScrollParent.js?v=2be83490:15:26)
    at getScrollParent (getScrollParent.js?v=2be83490:15:10)
    at listScrollParents (listScrollParents.js?v=2be83490:19:22)
    at Object.setOptions (createPopper.js?v=2be83490:70:19)
    at createPopper (createPopper.js?v=2be83490:215:14)
    at Object.fn (PopperUnstyled.jsx:133:24)
    at runComputation (dev.js:695:22)
    at updateComputation (dev.js:678:3)
    at runTop (dev.js:783:7)

**Additional context**
It happens randomly.

**Comment by atomiks** [comment] 2023-04-01 09:33
This cannot be debugged without a reproduction and looks like it could be a MUI bug.

We are closing issues for Popper to focus on tracking Floating UI, but PRs are still being accepted.

**Closed by atomiks** 2023-04-01 09:33 UTC
Labels: Bug, NEEDS: triage
