### ISSUE TITLE
FloatingArrow: "`NaN` is an invalid value for the `left` css style property" when running tests

### ISSUE THREAD

**Issue by mjcampagna** [floating-ui/floating-ui#2311] opened 2023-05-03 18:53 UTC
**Describe the bug**

We are seeing the following error when running our test suite for components which include floating-ui and the `FloatingArrow` component.

```
console.error
      Warning: `NaN` is an invalid value for the `left` css style property.
          at svg
          at FloatingArrow (/Users/mjcampagna/Glue/glue-web/node_modules/@floating-ui/react/dist/floating-ui.react.umd.js:101:9)
```

Tests are run with Jest and React Testing Library.

I believe we used to see this error (and suppressed it!) in the test environment when floating-ui positioned its tooltips, resulting from the window now being defined, or client rectangle failures. That was using an older version; the latest version of floating-ui seems to have fixed this, but not for the `FloatingArrow` component.

For now, we're hiding arrows while running tests, e.g. `process.env.NODE_ENV === "test"`.

**Comment by atomiks** [comment] 2023-05-05 03:37
Does it go away if you add:

```js
if (!floating) return null;
```

After the DEV statement here:

https://github.com/floating-ui/floating-ui/blob/b8d1fd5854333b688ddc9ee2a171f6453fcdbcab/packages/react/src/components/FloatingArrow.tsx#L72-L81

**Comment by meruyert93** [comment] 2023-05-12 21:02
Hey @atomiks 
I am also experiencing the same issue. I hope it will be fixed soon :) 

I have also found interesting observation. If I do 
```
jest.mock('@floating-ui/react', () => ({
  ...jest.requireActual('@floating-ui/react'),
}));
```

and like this: 
```
  beforeEach(() => {
    jest
      .mocked(useFloating)
      .mockImplementation(jest.requireActual('@floating-ui/react').useFloating);
    jest
      .mocked(useHover)
      .mockImplementation(jest.requireActual('@floating-ui/react').useHover);
    jest
      .mocked(useInteractions)
      .mockImplementation(
        jest.requireActual('@floating-ui/react').useInteractions,
      );
  });
```
The warning is gone. It is a bit weird and I cannot find the explanation. There is no need actually to require actual one because the component is using real module. However, it is a bit strange how it helps, maybe `requireActual` is not actually requiring, but maybe some kinda simulating it.  This is actually question to jest. Just out of curiosity, maybe do you have any idea how it could help?

However, ofc, it is not the solution. Therefore, looking forward to see fix for this one! Thanks a lot in advance!

**Closed** 2023-05-13 13:56 UTC
Labels: Bug

**Comment by oleksandr-danylchenko** [comment] 2024-08-23 14:44
I was able to replicate the issue in the non-testing environment 🙌🏻 
![image](https://github.com/user-attachments/assets/54db2431-a9e1-48f4-b59f-606eeb2847a3)
It happens when the content of the floating element collapses before the floating element closes. This is relevant when the content presence is controlled from the external storage.

**Comment by atomiks** [comment] 2024-08-25 11:03
Please make an issue w/ a reproduction, otherwise it will get lost and not fixed

**Comment by oleksandr-danylchenko** [comment] 2024-08-27 12:10
UPD: the issue I had is unrelated to the original submission. 
The `NaN` exception was caused by the virtual reference, which was returning an empty `DOMRectList` from the `getClientRects` function.
![image](https://github.com/user-attachments/assets/43c26861-f5ec-4752-873e-3fe853ebe5e2)
