### ISSUE TITLE
[DOM] The positioning calculation is incorrect in the scale scene

### ISSUE THREAD

**Issue by clfeng** [floating-ui/floating-ui#2012] opened 2022-12-07 08:35 UTC
## Reproduction link
https://github.com/clfeng/floating-ui-scale-bug-demo

### clone project
git clone https://github.com/clfeng/floating-ui-scale-bug-demo.git

### Startup project
yarn install;
yarn dev;

### explain 
The project provides two pages; 
http://localhost:5173/#/origin: This page is an example of the effect of float-ui without body scaling

http://localhost:5173/#/scale：This page is an example of the body scaling effect of float-ui

Through the comparison of the above two examples, it can be clearly seen that the position calculation in the scale scene is incorrect

more detail: https://github.com/clfeng/floating-ui-scale-bug-demo

### Environment Info

Browsers:
    Chrome: 107.0.5304.121
    Firefox: 77.0.1
    Safari: 14.1.2
  npmPackages:
    "@floating-ui/dom": "^1.0.8"

**Comment by atomiks** [comment] 2022-12-07 08:50
Thanks for posting it here, I confirmed that https://github.com/floating-ui/floating-ui/pull/2011 fixes it.

**Comment by atomiks** [comment] 2022-12-07 10:21
This is now fixed as of `@floating-ui/dom` `v1.0.9`

**Comment by clfeng** [comment] 2022-12-08 02:26
in this demo: https://github.com/clfeng/floating-ui-scale-bug-demo
i haved upgraded @floating-ui/dom to 1.0.9, but the bug is still exits;

in chrome browser:
the origin page performance:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/20736207/206340803-273cc44e-02ef-4988-9263-24a48a2f6c70.png">

the scale page performance:
<img width="514" alt="image" src="https://user-images.githubusercontent.com/20736207/206340861-92ccff94-68e6-4918-9386-e47487d9b517.png">

Compared with the above two examples, it can be found that the bug still exists；
*The scale page is displayed normally under safari, there may be browser compatibility issues *

**Comment by atomiks** [comment] 2022-12-08 02:42
I tested the fix with the original one: https://github.com/clfeng/idux-scale-bug-demo
Is the tooltip inside the same container as the button?

**Comment by atomiks** [comment] 2022-12-08 02:54
Seems to be a separate issue with transforms not related to clipping, but rather the initial anchor positioning. At least from what I can tell that's lower priority to fix as it's easier to workaround, but I'm not sure why it's wrong in that case...

**Comment by sallerli1** [comment] 2022-12-08 07:52
I tested the issue and found that the calculated scale seems to have a little deviation from the actual scale.

![image](https://user-images.githubusercontent.com/28892824/206389602-7415ba8f-f52b-49d5-a016-30c4c9b49957.png)
![image](https://user-images.githubusercontent.com/28892824/206389655-57c33d63-98ff-44bb-a6bd-bd69154cdc34.png)
![image](https://user-images.githubusercontent.com/28892824/206389810-51fa209e-d870-4b29-af3c-a2c76160b0df.png)



from what I saw, the calculated scale using size of rect and offset size was 1.74 and it should be 1.77, and when I change the scale to what it should be, the issue is no more.

yet I do not know how to workaround this

**Comment by sallerli1** [comment] 2022-12-08 08:13
I think this might be caused by the offset size only providing integer, I calculated using getComputedStyle and it was consistent with the actual scale

**Comment by atomiks** [comment] 2022-12-08 08:14
Nice find @sallerli1 

I actually added a new platform method called `getScale`, which you could override per-instance and manually pass in the scale if that detection doesn't work automatically.

```js
import {platform} from '@floating-ui/dom';

computePosition(a, b, {
  platform: {
    ...platform,
    getScale: () => ({x: 2, y: 1.77963})
  }
});
```

**Comment by atomiks** [comment] 2022-12-08 08:16
> I think this might be caused by the offset size only providing integer, I calculated using getComputedStyle and it was consistent with the actual scale

Does it return something easily parse-able, even if the element is inheriting scale?

**Comment by sallerli1** [comment] 2022-12-08 08:26
not that I know of, I am thinking about overwriting this using getComputedStyle in our lib，and if this works fine, I'll keep u updated

**Comment by clfeng** [comment] 2022-12-08 08:28
The reason for the inconsistent performance of the scale page in chrome and safari is mainly that the calculated zoom ratio of the body is different
The specific reason is as mentioned by @sallerli1

**Comment by clfeng** [comment] 2022-12-08 08:29
> 

The reason for the inconsistent performance of the scale page in chrome and safari is mainly that the calculated zoom ratio of the body is different
The specific reason is as mentioned by @sallerli1

**Comment by atomiks** [comment] 2022-12-08 08:34
Ok so, the only element that is being checked for scale is the `offsetParent`, so the `getComputedStyle` technique should work fine. It returns the `matrix(...)` function that you could extract the scale out of.

The `getScale` method is only used in `detectOverflow` while the internal function is used elsewhere which is something that should be fixed (to always use the custom platform method)

**Comment by sallerli1** [comment] 2022-12-08 09:08
> The `getScale` method is only used in `detectOverflow` while the internal function is used elsewhere which is something that should be fixed (to always use the custom platform method)

I think I just got stuck with this, overwriting the plaform doesn't really work because of it

**Comment by sallerli1** [comment] 2022-12-09 07:36
@atomiks thanks!!

however, is there any plan to refactor this logic to always use `scale` method passed from platform?

because computed transform attr is 'none' though it's ancestor is being scaled, the `matrix` technique is not really working in this situation.

and I was using

```ts
parseFloat(getComputedStyle(element).width.replace(/px$/))
```
to replace the offsetWidth(and so is height)

**Comment by sallerli1** [comment] 2022-12-09 07:38
And if there is no plan lately,  I intend to add a middware to fix the miscalculation caused by offset size

**Comment by atomiks** [comment] 2022-12-09 07:50
I think it adds like another 0.1 KB so I'd rather not unless it really has a good use case

> because computed transform attr is 'none' though it's ancestor is being scaled, the matrix technique is not really working in this situation.

Does my PR not fix the issue? (The PR doesn't fix the scenario when BOTH the offsetParent & reference elements have a scale though - but it should use the correct scale number).

**Comment by atomiks** [comment] 2022-12-11 08:31
OK I just realized you were highlighting the reference element's scale, not the offsetParent's, and the tests I was doing did not catch this because the elements use full integer width/height values, but the button's size is computed via its content, giving it a fractional width/height, which appears to be the cause of the issue.

So one workaround currently is to give the reference a non-fractional (aka fixed) width/height, but that's obviously not great. Maybe the offsetParent must not have a fractional/computed size either though.

So to get the real scale, we need to traverse every ancestor of the given element, and find any element that has a `scale`. And we'd also need to handle nested scales, and do all of that as performantly as possible. 😞

**Comment by clfeng** [comment] 2022-12-12 02:27
> 

in my usage scenario, referenced elements are uncontrolled；
the getFinalScale should be a good way to fix bug; 

Some borderline scenarios sample code doesn't seem to handle
```js
let ret = 'scale(1.123, 1.8786)'.match(/scale\((\d+)(\.\d+)?\)/) // ret is null

```

**Comment by atomiks** [comment] 2022-12-12 02:29
ChatGPT doesn't know the string is different, this PR handles everything https://github.com/floating-ui/floating-ui/pull/2019, but I need to add the caching PR first (and cache the scale calls) because the perf is poor.

**Comment by clfeng** [comment] 2022-12-12 03:12
> OK I just realized you were highlighting the reference element's scale, not the offsetParent's, and the tests I was doing did not catch this because the elements use full integer width/height values, but the button's size is computed via its content, giving it a fractional width/height, which appears to be the cause of the issue.
> 
> So one workaround currently is to give the reference a non-fractional (aka fixed) width/height, but that's obviously not great. Maybe the offsetParent must not have a fractional/computed size either though.
> 
> So to get the real scale, we need to traverse every ancestor of the given element, and find any element that has a `scale`. And we'd also need to handle nested scales, and do all of that as performantly as possible. 😞
> 
> Hmm, I guess accessing only offsetParents traversing up the tree should be pretty quick:
> 
> <img alt="Screenshot 2022-12-11 at 7 51 34 pm" width="686" src="https://user-images.githubusercontent.com/22450188/206894694-ab495012-91aa-4638-8100-ac7156d5765d.png">

What confuses me is why we have to recurse to get the zoom ratio；
Through the following method, we can directly calculate the final scaling ratio：
element.getBoundingRect().height / parseFloat(getComputedStyle(element).height.replace(/px$/, ''))

**Comment by clfeng** [comment] 2022-12-12 03:13
What confuses me is why we have to recurse to get the zoom ratio；
Through the following method, we can directly calculate the final scaling ratio：
```js

element.getBoundingRect().height / parseFloat(getComputedStyle(element).height.replace(/px$/, ''))
```

**Comment by atomiks** [comment] 2022-12-12 03:25
@clfeng you're right 😄 that's much better — didn't think it would return a fractional value, thanks! Going to update the PR.

**Closed** 2022-12-12 03:42 UTC
Labels: Bug

**Comment by atomiks** [comment] 2022-12-12 04:31
@clfeng unfortunately I found some elements can return `auto` for that value...
