### ISSUE TITLE
After upgrade to latest, floating-ui portal gets id=undefined

### ISSUE THREAD

**Issue by smellai** [floating-ui/floating-ui#2778] opened 2024-02-05 09:36 UTC
**Describe the bug** 

After updating to .9, something looks wrong with the generation of the id for a floating ui portal

**Expected behavior** 
I expect a floating-ui-N id to be generated.

**Screenshots** 
Snapshot of the generated HTML:

![Screenshot 2024-02-05 alle 10 32 51](https://github.com/floating-ui/floating-ui/assets/1763268/0e40395f-191c-4330-a628-727873e13365)

**Context:**

- Version 0.26.9

**Comment by atomiks** [comment] 2024-02-05 10:20
Is this only in snapshot tests? In the browser it's defined with both conditional and unconditional rendering.

**Comment by smellai** [comment] 2024-02-05 11:17
Yes, you're right, it happens only in jest snapshots, any idea why it could be?

**Comment by atomiks** [comment] 2024-02-11 07:54
I couldn't reproduce this with React 17 or 18 with a basic snapshot test using Vitest (both conditional and unconditional `FloatingPortal` rendering based on an `open` state), using latest `@testing-library/react` and `jsdom`. Maybe it's a React 16 problem in a testing env, or something else, but it doesn't seem to be an actual bug. Feel free to provide a reproduction if you have the ability, but for now, I'm closing due to lack of ability to reproduce the issue.

**Closed by atomiks** 2024-02-11 07:54 UTC

**Comment by smellai** [comment] 2024-02-22 13:39
Hi, I finally managed to set up a reproduction: https://stackblitz.com/edit/vitejs-vite-erxqfe?file=src%2F__snapshots__%2FPopover.spec.js.snap

you can see `id="undefined"` at line 19

**Comment by atomiks** [comment] 2024-02-22 13:49
Have you tried:
- Upgrading to React 18, which uses the native `useId()` hook and has better perf (I'm going to drop React 17 support when React 19 comes out in a few months anyway)
- Adding `act(async () => {})` after the `render()` call in the test async (it breaks in Stackblitz, not sure why)
- Avoiding snapshot tests which can easily break when implementation details of this library change (such as here) even though it's not actually broken for real users

**Comment by mihkeleidast** [comment] 2024-05-16 12:03
@atomiks I see this error in the browser with React 17.

1. Took the Tooltip example from docs
2. Downgraded React to 17, upgraded floating-ui to latest
3. https://codesandbox.io/p/sandbox/upbeat-lake-r5qdz4

In devtools, the ID is undefined:
![image](https://github.com/floating-ui/floating-ui/assets/1892091/2eebb0a2-6639-463e-b56e-3624c0a0c30f)

**Comment by atomiks** [comment] 2024-05-18 03:16
I don't see the issue with `17.0.1` on the latest? [Demo](https://codesandbox.io/p/sandbox/crazy-sara-3ck4qq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwbja9pa00073b6ipj1wvgyw%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwbja9pa00033b6ie991g7mq%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwbja9pa00043b6i6tldhk7q%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwbja9pa00063b6i7oi5hz1h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwbja9pa00033b6ie991g7mq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwbja9pa00023b6ixxlr2sna%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwbja9pa00033b6ie991g7mq%2522%252C%2522activeTabId%2522%253A%2522clwbja9pa00023b6ixxlr2sna%2522%257D%252C%2522clwbja9pa00063b6i7oi5hz1h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwbja9pa00053b6ixesru4d0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwbja9pa00063b6i7oi5hz1h%2522%252C%2522activeTabId%2522%253A%2522clwbja9pa00053b6ixesru4d0%2522%257D%252C%2522clwbja9pa00043b6i6tldhk7q%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwbja9pa00043b6i6tldhk7q%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) (your Sandbox is private btw)

**Comment by atomiks** [comment] 2024-05-18 04:15
Found fix here: https://github.com/floating-ui/floating-ui/pull/2908 (it happens in only a somewhat specific case)

**Comment by mihkeleidast** [comment] 2024-05-18 06:58
Thanks, the fix & reasoning makes sense!

> your Sandbox is private btw

Ugh, codesandbox makes it too many clicks nowadays to fork and share something. Fixed it now.

Re: updating to React 18 - yeah, totally on the roadmap, just it takes time as we have some enormous amount of ancient enzyme tests to refactor, as it does not work very well with newer React versions. In a large company this takes a long time unfortunately.
