### ISSUE TITLE
Avoid obscuring focused elements

### ISSUE THREAD

**Issue by tay1orjones** [floating-ui/floating-ui#2601] opened 2023-10-16 20:11 UTC
**Is your feature request related to a problem? Please describe.**

WCAG 2.2 recently reached recommendation status, and within it there is a new requirement regarding focus that relates to floating elements.

> [Success Criterion 2.4.11 Focus Not Obscured (Minimum)](https://www.w3.org/TR/WCAG22/#focus-not-obscured-minimum)
>
> When a [user interface component](https://www.w3.org/TR/WCAG22/#dfn-user-interface-components) receives keyboard focus, the component is not entirely hidden due to author-created content.

**Describe the solution you'd like**

I'd like elements positioned via floating-ui to automatically reflow if they obscure (are on top of) an element that receives focus.

This most commonly impacts things like toast notifications as they can be non-user-generated and shouldn't obscure focus to meet the new requirement.

**Describe alternatives you've considered**

Creating our own detection helper that listens to all onFocus changes on the window, and compares that focused elements' size/position with an element we know can potentially overlay it (like a notification, for instance). If the notification fully obscures the element with focus, re-render the notification in a different location so that focus is no longer obscured.

**Additional context**

This new requirement is scoped to elements created by the author/dev, and does not apply to elements created based on user interaction. So it won't typically apply to floating elements created by actions the user takes such as tooltips. Tooltips are pretty much always opened by the user via focus/hover/click/etc.

Still I think this would be a worthwhile middleware to have as an option for elements rendered with the help of this library.

**Comment by atomiks** [comment] 2023-10-16 22:24
I think this is a duplicate of https://github.com/floating-ui/floating-ui/issues/1440

**Comment by tay1orjones** [comment] 2023-10-17 16:53
Ah yes, my bad. They do look very related. I searched the repo but didn't see that one. Feel free to close as a dupe, I'll make a comment over there about this stuff.

**Comment by atomiks** [comment] 2023-11-05 01:51
Yeah, it's good to link it with different wording in cases of search anyway.  Getting it to work well is kind of tricky I've found which is why it hasn't been merged or released as a feature yet.

Going to close this as a duplicate though.

**Closed by atomiks** 2023-11-05 01:51 UTC
