### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by csantos1113** [floating-ui/floating-ui#1740] opened 2022-06-06 17:12 UTC
@atomiks 

> You could disable the elementResize option and update manually when content changes.

Unfortunately I can't do this. I'm not changing the content, it's just due to the repositioning of the same tooltip itself

> I've never seen that error when it's near the edge of the viewport. Does it happen in incognito mode? Seems like extensions could interfere based on the SO thread?

I did my best to replicate the issue in codesandbox: https://codesandbox.io/s/elated-sunset-1ugji2?file=/src/App.tsx

See the video with the steps:

https://user-images.githubusercontent.com/9648559/172205861-d11354db-01dd-48f3-af33-28e804b38f09.mov

FYI: I had to add this to correctly track the "loop limit exceeded":
```
  useEffect(() => {
    window.onerror = console.error;
  }, []);
```

_Originally posted by @csantos1113 in https://github.com/floating-ui/floating-ui/issues/1739#issuecomment-1147656061_

**Comment by atomiks** [comment] 2022-06-10 01:07
The error is harmless, you just need to find a way to suppress it. 

`elementResize: false` still keeps the window resize listeners, so it should be fine if you aren't changing any content.

**Comment by seyfer** [comment] 2022-06-15 07:35
@csantos1113 @atomiks have you thought about applying this solution?

```
const resizeObserver = new ResizeObserver(entries => {
   // We wrap it in requestAnimationFrame to avoid this error - ResizeObserver loop limit exceeded
   window.requestAnimationFrame(() => {
     if (!Array.isArray(entries) || !entries.length) {
       return;
     }
     update(entries);
   });
});
```

if you think its viable let me create PR

**Comment by atomiks** [comment] 2022-10-21 20:11
**Update:**

For anyone having these issues, all you need to do is set `width: max-content` CSS on the floating element. 

I am adding a section in the docs that explains why this is necessary, and another alternative solution too.

**Comment by liamaharon** [comment] 2023-05-09 17:43
I was able to resolve this by applying a debounce of 1ms to my `size` `apply` function:

```typescript
    const { context, x, y, reference, floating, strategy } = useFloating({
      open,
      onOpenChange: setOpen,
      whileElementsMounted: autoUpdate,
      middleware: [
        // Debounce to fix annoying ResizeObserver loop limit exceeded error
        // https://github.com/floating-ui/floating-ui/issues/1740
        size({
          apply: debounce(({ rects, availableHeight, elements }) => {
            Object.assign(elements.floating.style, {
              width: `${rects.reference.width}px`,
              maxHeight: `${availableHeight}px`,
            })
          }, 1),
        }),
        offset(-OVERLAP),
      ],
    })
```

**Comment by atomiks** [comment] 2023-05-09 18:10
You can probably use `requestAnimationFrame` inside of the `apply` function without needing `debounce`, but that assignment should ideally be sync :\ 

The `width: max-content` fix works if the floating element is positioned using layout (`top`/`left`, instead of `transform`) because the document will cause it to resize at the edge. In this case you're experiencing something else. (I've never seen it though, personally). Maybe there are ways to prevent it from ever appearing with `size` + `autoUpdate`'s `ResizeObserver`.

**Comment by atomiks** [comment] 2023-05-18 19:21
Re-opening as there should be a way to ignore the error for the `size.apply` case without the rAF wrapper (which causes subtle bugs). It likely can be achieved by adding a flag on the node in `size`, and checking within the `ResizeObserver` callback if the flag is present (and skipping the `update` call).

**Comment by atomiks** [comment] 2023-05-18 19:42
@npearson72 since I can't really reproduce it, can you tell me if this fixes the issue for you locally:

> <relevant_file>.js depends on your bundler as to which is being chosen in dev

- In `node_modules/@floating-ui/core/dist/<relevant_file>.js` (Core package):

In the `size` middleware add:

```diff
+    elements.floating.__$size = 1;

    await apply({...state, availableWidth, availableHeight});

    const nextDimensions = await platform.getDimensions(elements.floating);

    if (width !== nextDimensions.width || height !== nextDimensions.height) {
      return {
        reset: {
          rects: true,
        },
      };
    }

+    delete elements.floating.__$size;
```

- Then, in `node_modules/@floating-ui/dom/dist/<relevant_file>.js` (DOM package):

In `autoUpdate add the guard:

```diff
    observer = new ResizeObserver(() => {
+      if (!('__$size' in floating)) {
+        update();
+      }
    });
```

**Comment by npearson72** [comment] 2023-05-18 21:11
Interesting. I believe this has fixed it. I say "believe" because it would fire off somewhat intermittently. I never pinned it down to a specific UI interaction, but noticed the error appearing sometimes when triggering a popover.

I just banged on it quite a bit and have not seen the error. Interestingly it also seems to have resolved a UI quirk I was seeing with flip firing off in unpredictable ways in React when my component is first mounted. Possibly related?

**Comment by atomiks** [comment] 2023-05-18 21:22
I'm glad it fixed it - yes `flip` + `size` can have quirks if not set up right so it seems it can solve that as well.

**Comment by npearson72** [comment] 2023-05-18 21:25
Thanks again for looking into this

**Comment by atomiks** [comment] 2023-05-25 21:48
I'd like this to be fixed, but can't reproduce the problem when using `size`. So if you want to fix it, please make a PR with a potential fix because I can't work on it. It seems like https://github.com/floating-ui/floating-ui/pull/2335 doesn't work.

- **First, make sure your floating element has `width: max-content` (or a fixed width)** to prevent it from resizing at the boundary edge if it's being positioned using layout (`top`/`left`) rather than transform CSS. This is the most common cause of the error and usually fixes it.
- If you're still getting the error, you can just ignore it because it's harmless. If it's generating a modal overlay dialog and blocks your work, find ways to suppress the dialog or error (via `window.onerror`).
- If you can't do this for whatever reason, and it's caused by `size`, add `requestAnimationFrame` to the assignment inside your `apply` function. This causes some slight visual bugs but usually isn't _too_ severe. I don't recommend it, but it's a quick patch if the above points fail.
- If it's caused by something else other than `size`, set the `elementResize: false` option in `autoUpdate`. If the floating element or reference element resize, update the position manually instead in this case.

**Comment by npearson72** [comment] 2023-05-25 21:50
Thanks @atomiks

**Comment by harry-gocity** [comment] 2023-06-26 10:51
> I'd like this to be fixed, but can't reproduce the problem when using `size`. 

Hi @atomiks, I have a reproduction for you, although it may be from a problem that exists in userland and not your library. 

I've forked the autocomplete example [here](https://codesandbox.io/s/unruffled-chebyshev-nyzwv6?file=/src/App.tsx) and replicated what is causing the issue for us in our component library:

- I've added an `Input` component that uses a `forwardRef` to render an `input` wrapped in a `div`
    - The wrapping div provides focus style, specifically different borders when focussed
    -  The `Input` fills the available space in the wrapping div
    - The wrapping div may normally have other children, like appended/prepended text, or a conditionally included icon, but they're not needed for the repro
-  The `Autocomplete` that uses floating-ui then uses the `Input` component

It seems like due to the focus behaviour of the wrapping div in the `Input` component, the input within it is effectively getting resized when focussed. And with the `forwardRef`, which we want to reference the actual input element for other behaviours, floating-ui is sizing based on this input, and not the outer wrapping `div`. This then causes a the resize observer error to be thrown.

Based on suggestions in https://github.com/floating-ui/floating-ui/issues/1740#issuecomment-1563544849

- Setting `width: max-content` for us is not an option as the floating element should be the width of the fixed one,
- Ignoring the error is not practical, as we have to ask every team using this lib to update their monitoring tool e.g. Sentry with the exclusion
- `requestAnimationFrame` seems to fix the issue
- `elementResize: false` seems to fix the issue

Out of those last two options - which would you recommend? I was leaning towards the `elementResize`, as our floating element still stays anchored on scroll and responds to be the correct width width on window resize, and this avoids any possible visual issues with `requestAnimationFrame`. 

I guess the `apply` + width setting we have is similar to https://github.com/floating-ui/floating-ui/issues/1740#issuecomment-1540600819, for which you say `elementResize: false` is fine in https://github.com/floating-ui/floating-ui/issues/1740#issuecomment-1540639488, but just wanted to check.

**Comment by atomiks** [comment] 2023-06-26 11:12
@harry-gocity thanks for the repro. Not really sure why it's happening exactly there, but in your case it looks like you can keep `availableHeight` sync and wrap the other one in rAF. This avoids visual bugs and removes the error while retaining resize updates, which is the best scenario:

```js
requestAnimationFrame(() => {
  elements.floating.style.width = `${rects.reference.width}px`
})
elements.floating.style.maxHeight = `${availableHeight}px`
```

**Comment by harry-gocity** [comment] 2023-06-26 12:14
> looks like you can keep availableHeight sync and wrap the other one in rAF.
> nevermind, still seems to happen with availableHeight one too

wrapping with `requestAnimationFrame` as you initially described seems to work fine for us, no error thrown - or am I missing something?

**Comment by atomiks** [comment] 2023-06-26 12:46
I got the error if the floating element was scrollable with a lot of content in the sandbox (so `height` > `maxHeight`, was having an effect).

Removing the layout shift to me seems like the best option since layout shift it's great UX to begin with, which also seems to fix the issue.

**Closed** 2023-06-29 05:51 UTC
Labels: Bug

**Comment by devanshgawai** [comment] 2023-07-04 10:03
> The error is harmless, you just need to find a way to suppress it.
> 
> `elementResize: false` still keeps the window resize listeners, so it should be fine if you aren't changing any content.

where shall I write elementResize: false?

**Comment by atomiks** [comment] 2023-07-04 10:39
@devanshgawai try upgrading to the latest version of `@floating-ui/dom` first (`1.4.3`)

You pass `elementResize: false` to `autoUpdate`, but make sure you update first and have `width: max-content` set on your floating element before that since it shouldn't occur anymore (hopefully).

That comment lacks context since it was a continuation of the discussion but search results won't show that :\  - going to update the OP and reply

**Comment by harry-gocity** [comment] 2023-07-05 11:12
Thanks @atomiks, I'm out this week but will give this a go when I'm back 🙌🏻

**Comment by meri-maki** [comment] 2023-07-28 18:02
Hi! I'm facing the same issue with "@floating-ui/react": "^0.24.8",
I'm using reusable tooltip component based on official example
https://codesandbox.io/s/xenodochial-grass-js3bo9?file=/src/App.tsx

I've set width of my tooltip to fixed via css, but could you please explain where should I put autoUpdate with elementResize: false.. It's a bit unclear in docs how it should be used in react...
