### ISSUE TITLE
[React] I need to offset the <FloatingArrow> by one pixel

### ISSUE THREAD

**Issue by hornta** [floating-ui/floating-ui#2563] opened 2023-09-20 10:34 UTC
I'm using the `<FloatingArrow>` component to render the arrow and it works great, but I would like to always offset it by one pixel so that the last white stroke lies above the floating element so that it looks like one contineous stroke. This would be a nice addition to this arrow component.

```ts
<FloatingArrow
  ref={arrowRef}
  context={floatingContext}
  width={ARROW_WIDTH}
  height={ARROW_HEIGHT}
  strokeWidth={1}
  tipRadius={1}
  className="fill-white [&>path:first-of-type]:stroke-gray-300[&>path:last-of-type]:stroke-white"
/>
```

![image](https://github.com/floating-ui/floating-ui/assets/4553604/e7d28f84-ac9b-4ba2-aa0b-df2fa38e3661)

I could add a `my-[-1px]` class to the arrow and that works for when it's placement is bottom but not at the side:

![image](https://github.com/floating-ui/floating-ui/assets/4553604/3d40f969-1093-4e5c-b008-45a631aabb57)

![image](https://github.com/floating-ui/floating-ui/assets/4553604/ea2d9382-6bc8-4eb3-ba4c-ce950c04e1ae)

**Comment by hornta** [comment] 2023-09-20 13:08
It's not zoomed but I am using the `useTransitionStyles` and that's almost taken line by line from the reusable popover example. 

Result: https://play.tailwindcss.com/rsyjYOxDLA

My component:
```ts
const ARROW_WIDTH = 14;
const ARROW_HEIGHT = 7;

const Content = forwardRef<HTMLElement, ComponentProps<"div">>(function Content(
  { children, style, ...rest },
  propRef
) {
  const {
    context: floatingContext,
    arrowRef,
    floatingStyles,
    middlewareData,
    getFloatingProps,
    ...context
  } = usePopoverMenuContext();
  const ref = useMergeRefs([context.refs.setFloating, propRef]);

  const arrowX = middlewareData.arrow?.x ?? 0;
  const arrowY = middlewareData.arrow?.y ?? 0;
  const transformX = arrowX + ARROW_WIDTH / 2;
  const transformY = arrowY + ARROW_HEIGHT;

  const { styles: transitionStyles, isMounted } = useTransitionStyles(
    floatingContext,
    {
      duration: 100,
      initial: {
        opacity: 0,
        transform: "scale(0.95)",
      },
      common: ({ side }) => ({
        transformOrigin: {
          top: `${transformX}px calc(100% + ${ARROW_HEIGHT}px)`,
          bottom: `${transformX}px ${-ARROW_HEIGHT}px`,
          left: `calc(100% + ${ARROW_HEIGHT}px) ${transformY}px`,
          right: `${-ARROW_HEIGHT}px ${transformY}px`,
        }[side],
      }),
    }
  );

  if (!isMounted) return null;

  const floatingProps = getFloatingProps({ className: "z-10", ...rest });

  return (
    <FloatingPortal>
      <FloatingFocusManager context={floatingContext}>
        <div
          ref={ref}
          style={{
            ...floatingStyles,
            ...style,
            zIndex: style?.zIndex ?? 1400,
          }}
          {...floatingProps}
        >
          <div
            style={transitionStyles}
            aria-labelledby={context.labelId}
            aria-describedby={context.descriptionId}
          >
            {children}
            <FloatingArrow
              ref={arrowRef}
              context={floatingContext}
              width={ARROW_WIDTH}
              height={ARROW_HEIGHT}
              strokeWidth={1}
              tipRadius={1}
              className="fill-white [&>path:first-of-type]:stroke-grey-300 [&>path:last-of-type]:stroke-white my-[-1px]"
            />
          </div>
        </div>
      </FloatingFocusManager>
    </FloatingPortal>
  );
});
```

**Comment by atomiks** [comment] 2023-09-20 13:37
Strange as I can't reproduce it locally and I'm not sure how to get that Tailwind result. A CodeSandbox repro would be better.

This PR simplifes some of the path logic, does it help if you change it locally? https://github.com/floating-ui/floating-ui/pull/2423/files (you need to remove the `last-of-type` target.)

**Comment by hornta** [comment] 2023-09-20 14:26
https://github.com/hornta/vitejs-vite-oyyhgd/tree/main

It's reproducible in either GH codespaces or stackblitz.

**Comment by atomiks** [comment] 2023-09-20 15:11
You're putting the border on the `children` of the floating element but the arrow is positioned relative to the floating element. If you put the border on the floating element instead then it's fine.

**Comment by hornta** [comment] 2023-09-20 17:43
I had that at first but then I was having some weird jumping issue with the arrow. As long as the transition was going on the arrow is correctly positioned but not when it's done.

![35aa81e6-7dc8-4197-9f0c-15220710424f](https://github.com/floating-ui/floating-ui/assets/4553604/154f939d-3486-4902-8ecc-02e19cb04d8c)

**Comment by atomiks** [comment] 2023-10-02 05:01
Since this has a workaround and seems to be related to browser rendering issues, I am going to close this. But PRs welcome if better solutions are found for this issue.

**Closed by atomiks** 2023-10-02 05:01 UTC
Labels: has workaround

**Comment by hmaesta** [comment] 2023-10-04 17:18
I'm having this issue as well. 

The arrow is correctly positioned, but since my popover has a border it looks like it's `1px` away from where it should be when <kbd>top</kbd> or <kbd>bottom</kbd> positioned; or `2px` when <kbd>left</kbd> and <kbd>bottom</kbd> positioned.

Applying a negative margin to my child object caused the same bug described in this thread.

https://github.com/floating-ui/floating-ui/assets/741969/5e0091f4-7020-47ef-be18-12a0642de218

I believe having an `offset` prop in `FloatingArrow` would fix this issue. My idea would be to use like so:

```tsx
const offsetMap: Map<Placement, number> = new Map(
  [
    ['top', 1],
    ['bottom', -1],
    ['right', 2],
    ['left', -2],
  ]
);

<FloatingArrow
   (...) 
   context={context}
   offset={offsetMap.get(context.placement.split("-")[0])}
/>
```

For the above example, the expected dynamic computed style would be:
| Placement | Computed dynamic style   |
|-----------|--------------------------|
| top       | top: calc(100% + 1px)    |
| bottom    | bottom: calc(100% - 1px) |
| left      | left: calc(100% - 2px)   |
| right     | right: calc(100% + 2px)  |

**Comment by atomiks** [comment] 2023-10-05 09:21
Doesn't `<FloatingArrow style={{ transform: 'translateY(-1px)' }} />` do that?

**Comment by hmaesta** [comment] 2023-10-05 13:17
Ohh, I haven't even considered `style` because that was already being defined and I wasn't expecting it to get merged.
It worked like a charm. 👌 

So silly that I went full-over-engineering and haven't thought about style merging. 
Thank you, James.
